# Table of Contents

1. [Git Basics](git_basics.md)
2. [Algorithm Complexity](algorithm_complexity.md)
3. [Sorting Algorithms](sorting_algorithms.md)
4. [Graph Algorithms](graph_algorithms.md)
5. [Prime Numbers](prime_numbers.md)
6. [Java Basics](java_basics.md)
7. [Java Data Types](java_data_types.md)
8. [Java Conditional Statements and Looping Constructs](java_conditional_statements.md)
9. [Java Object-Oriented Principles](java_object_oriented.md)
10. [Java Annotations](java_annotations.md)
11. [Java Interfaces](java_interfaces.md)
12. [Java Autoboxing and Unboxing](java_autoboxing.md)
13. [Java Data Structures and Algorithms](java_data_structures.md)
14. [Java Reading Data from Files](java_file_io.md)
15. [Java Collection Framework: Generics](java_generics.md)